In [1]:
import torch 

In [2]:
x = torch.ones(2,2,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y=x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
print(y.grad_fn)

In [7]:

z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2, 2)
print(a.requires_grad)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
False
True


In [12]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
out.backward()

In [11]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-478.0965,  960.7063, -151.5809], grad_fn=<MulBackward0>)


In [17]:
y.data.norm()#2泛数

tensor(1083.7479)

In [16]:
/#二范数torch.sqrt((y**2).sum())

tensor(1083.7479, grad_fn=<SqrtBackward>)

In [18]:
y.grad_fn

In [19]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [20]:

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
