In [1]:
import torch
from torch import nn

x = torch.ones(3)
torch.save(x, 'x.pt')


In [2]:
x2 = torch.load('x.pt')
x2


tensor([1., 1., 1.])

## 存储列表

In [3]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list


[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

## 存储字典

In [5]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy


{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP,self).__init__()
        self.hidden=nn.Linear(3,2)
        self.act=nn.ReLU()
        self.output=nn.Linear(2,1)
    def forward(self,x):
        a =self.act(self.hidden(x))
        return self.output(a)
net = MLP()
net.state_dict()

OrderedDict([('hidden.weight', tensor([[-0.4040, -0.4986, -0.3230],
                      [ 0.3740,  0.2156, -0.5432]])),
             ('hidden.bias', tensor([ 0.1704, -0.2145])),
             ('output.weight', tensor([[-0.5466, -0.6281]])),
             ('output.bias', tensor([0.4228]))])

In [7]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [2715178626008, 2715178538872, 2715179651864, 2715138347480]}]}

In [16]:
nn.Linear(3,2)

Linear(in_features=3, out_features=2, bias=True)

In [12]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y


tensor([[True],
        [True]])

In [13]:
torch.randn(2, 3)

tensor([[-0.4336,  1.2627, -0.0159],
        [ 0.8191, -0.3242, -0.0058]])

In [14]:
torch.randn(3, 2)

tensor([[ 0.5325, -1.7422],
        [-0.0450,  0.1583],
        [-0.1277, -0.0246]])